// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxJboguDMIMvYL9-DEOOUlQ48QqUtOsk',
    appId: '1:206861061946:web:519fd91bb8c9f9a26d8a03',
    messagingSenderId: '206861061946',
    projectId: 'askuc-e1aba',
    authDomain: 'askuc-e1aba.firebaseapp.com',
    storageBucket: 'askuc-e1aba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDrJZR6kyaJkJial2NnklBWVOWtvqNd5k',
    appId: '1:206861061946:android:463bee107081ee766d8a03',
    messagingSenderId: '206861061946',
    projectId: 'askuc-e1aba',
    storageBucket: 'askuc-e1aba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQt2-T_F8f5GTUoxhZjC7S3k7qmsKwhg',
    appId: '1:206861061946:ios:fd79d33cfed876a96d8a03',
    messagingSenderId: '206861061946',
    projectId: 'askuc-e1aba',
    storageBucket: 'askuc-e1aba.firebasestorage.app',
    iosBundleId: 'com.example.askuc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwQt2-T_F8f5GTUoxhZjC7S3k7qmsKwhg',
    appId: '1:206861061946:ios:fd79d33cfed876a96d8a03',
    messagingSenderId: '206861061946',
    projectId: 'askuc-e1aba',
    storageBucket: 'askuc-e1aba.firebasestorage.app',
    iosBundleId: 'com.example.askuc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnxJboguDMIMvYL9-DEOOUlQ48QqUtOsk',
    appId: '1:206861061946:web:1e4d12d0129f36296d8a03',
    messagingSenderId: '206861061946',
    projectId: 'askuc-e1aba',
    authDomain: 'askuc-e1aba.firebaseapp.com',
    storageBucket: 'askuc-e1aba.firebasestorage.app',
  );
}
